apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat-db
  name: chat-db-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chat-db
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
        - image: mista123/chatdb:latest
          name: chat-db
          env:
            - name: DB_URL
              value: "cluster0.fyxpu.mongodb.net"
            - name: DB_USER
              value: "admin2"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets3
                  key: mongo_pass
            - name: DB_NAME
              value: "chat"
            - name: TOKEN_URL
              value: "http://51.132.211.245//:8081/v1/token"
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/health/live_check
              port: server
            initialDelaySeconds: 5
            periodSeconds: 10

---


apiVersion: v1
kind: Service
metadata:
  name: chat-db
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: chat-db